In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [44]:
def input_generator(num_location, num_home, starting_location):
    print(num_location)
    print(num_home)
    
    p = 0.6
    locations = [starting_location]
    homes = []
    edge_matrix = np.ones((num_location+1, num_location+1))
    for i in range(num_location):
        locations.append("location {}".format(i+1))
        for j in range(num_location+1):
            if i == j : 
                edge_matrix[i][j] = 0
            if j > i : 
                continue
            elif np.random.uniform(0,1) > p:
                edge_matrix[i][j] = 0
                edge_matrix[j][i] = 0
    for i in range(num_home):
        homes.append("home {}".format(i+1))
    
    print(locations)
    print(homes)
    print(edge_matrix)

In [47]:
input_generator(4, 3, "Soda")

4
3
['Soda', 'location 1', 'location 2', 'location 3', 'location 4']
['home 1', 'home 2', 'home 3']
[[0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
